"""text_filename

Revision ID: 5b04abc36d62
Revises: bed7c9a4b332
Create Date: 2022-02-12 18:55:15.093107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b04abc36d62'
down_revision = 'bed7c9a4b332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('text_filename', sa.String(), nullable=False))
    op.drop_column('documents', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'text_filename')
    # ### end Alembic commands ###
