"""doc-summary

Revision ID: bed7c9a4b332
Revises: bede968e75b0
Create Date: 2022-02-12 12:50:13.973201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed7c9a4b332'
down_revision = 'bede968e75b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
